# Generated by Django 3.1.2 on 2020-10-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.IntegerField(verbose_name='Влажность')),
                ('pressure', models.IntegerField(verbose_name='Атм. давление')),
                ('temp', models.IntegerField(verbose_name='Температура')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
        ),
    ]
